name: Top
version: '1.0-RELEASE'
main: org.akorpuzz.top.Top
api-version: '1.21'
softdepend: [Vault, PlaceholderAPI]
commands:
  top:
    description: Muestra el ranking de facciones
    usage: /top [p치gina]
    aliases: [fctop, factiontop]
  topplayers:
    description: Muestra el ranking de jugadores por dinero
    usage: /topplayers [p치gina]
    aliases: [playertop]
  topreload:
    description: Recarga la configuraci칩n del plugin
    usage: /topreload
  topupdate:
    description: Forzar actualizaci칩n del Top y snapshot de placeholders
    usage: /topupdate





