name: Top
version: '1.0-SNAPSHOT'
main: org.akorpuzz.top.Top
api-version: '1.21'
softdepend: [Vault]
commands:
  top:
    description: Muestra el ranking de facciones
    usage: /top [página]
    aliases: [fctop, factiontop]
  topplayers:
    description: Muestra el ranking de jugadores por dinero
    usage: /topplayers [página]
    aliases: [playertop]
  topreload:
    description: Recarga la configuración del plugin
    usage: /topreload
permissions:
  topfactions.use:
    description: Permite usar el comando /top
    default: true
  topfactions.reload:
    description: Permite recargar el plugin
    default: op


